### PR TITLE
Fix #3 setup mongoKeys when installing tools only

### LINKED ISSUE #3: MongoTools only | Setup fails
If you only want to install MongoTools the install fails :
`E: Unable to locate package mongodb-database-tools`

This is because 
```bash
echo "setup keys"
wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
sudo apt-get install gnupg
wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

echo "aptitude update"
sudo apt-get update
```

only runs in `setupMongoShell.sh`

### PR DESCRIPTION
**Pull request by boly38**
Fix #3 setup mongoKeys when installing tools only

### CODE REVIEW

File: setupMongoShell.sh [hunk 1]
```diff
@@ -1,16 +1,12 @@
...
-echo "aptitude update"
-sudo apt-get update
+if [ ! -f ./.setupMongoKeys ]; then
+  ./setupMongoKeys.sh
+fi
 
 echo "aptitude install mongodb-mongosh"
-sudo apt-get install -y mongodb-mongosh
+sudo
+} apt-get install -y mongodb-mongosh
```
Comment (boly38) [inline setupMongoShell.sh]: ?

**Comment by boly38** [comment]
job dont work because based on `@stable` :)
